spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Amir1376reall
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET:KudUrCLNF7tHdUhguuZIxe0PqZAXcW1pWz07Olu7qLYHj+wCR3iUXIeTkkfhaJIyBAXQ4BNOMgZrw+NDKkj+Og==}