-- =========================
-- INSERT CATEGORIES
-- =========================

INSERT INTO categories (name)
VALUES ('Running'),
       ('Football'),
       ('Basketball'),
       ('Fitness'),
       ('Cycling'),
       ('Outdoor'),
       ('Swimming'),
       ('Tennis');


-- =========================
-- INSERT PRODUCTS
-- =========================

INSERT INTO products (name, price, description, category_id)
VALUES ('Nike Air Zoom Pegasus 40',
        129.99,
        'Lightweight running shoes designed for daily training with responsive cushioning and breathable mesh upper.',
        1),
       ('Adidas Ultraboost Light',
        189.99,
        'Premium running shoes featuring Boost midsole technology for maximum comfort and energy return.',
        1),
       ('Puma Future Ultimate Football Boots',
        219.99,
        'Professional football boots with adaptive fit and superior traction for firm ground surfaces.',
        2),
       ('Nike Premier League Football',
        34.99,
        'Official size 5 football built for durability, precision flight, and consistent performance.',
        2),
       ('Wilson Evolution Basketball',
        79.99,
        'High-performance indoor basketball with soft composite cover and excellent grip.',
        3),
       ('Spalding NBA Street Basketball',
        29.99,
        'Durable outdoor basketball designed for asphalt courts and long-lasting performance.',
        3),
       ('Bowflex Adjustable Dumbbells 24kg',
        399.99,
        'Space-saving adjustable dumbbells suitable for full-body strength training at home.',
        4),
       ('Under Armour Training Gloves',
        24.99,
        'Breathable workout gloves with wrist support and anti-slip palm grip.',
        4),
       ('Fitbit Charge 6 Fitness Tracker',
        159.99,
        'Advanced fitness tracker with heart rate monitoring, GPS, and sleep tracking.',
        4),
       ('Giant Escape 3 Hybrid Bike',
        649.99,
        'Versatile hybrid bicycle ideal for commuting, fitness rides, and urban cycling.',
        5),
       ('Garmin Edge 540 Cycling Computer',
        349.99,
        'GPS cycling computer with performance analytics and turn-by-turn navigation.',
        5),
       ('CamelBak Hydration Backpack',
        89.99,
        'Lightweight hydration pack perfect for hiking, cycling, and outdoor adventures.',
        6),
       ('The North Face Borealis Backpack',
        129.99,
        'Durable outdoor backpack with ergonomic support and multiple storage compartments.',
        6),
       ('Coleman Sundome 4-Person Tent',
        149.99,
        'Weather-resistant camping tent with quick setup and spacious interior.',
        6),
       ('Speedo Fastskin Swim Goggles',
        39.99,
        'Professional swim goggles with anti-fog coating and UV protection.',
        7),
       ('Arena Powerskin ST Swim Jammer',
        99.99,
        'Competition swim jammer designed for hydrodynamics and muscle compression.',
        7),
       ('Babolat Pure Drive Tennis Racket',
        249.99,
        'Popular performance tennis racket offering power, spin, and control.',
        8),
       ('Wilson US Open Tennis Balls',
        14.99,
        'Official championship tennis balls with consistent bounce and durability.',
        8),
       ('Yonex Pro Tennis Backpack',
        74.99,
        'Premium tennis backpack with racket compartment and ventilated shoe pocket.',
        8),
       ('Reebok Speed Jump Rope',
        19.99,
        'Adjustable speed rope designed for cardio workouts, boxing, and endurance training.',
        4);